plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.spring'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
    id 'org.graalvm.buildtools.native'
}

group = 'xyz.chener.napt.client'
version = '0.0.1-SNAPSHOT'

dependencies {
    implementation project(":common")
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'io.netty:netty-all:4.2.10.Final'
    implementation 'com.google.protobuf:protobuf-java:4.34.0'
}


tasks.named('test') {
    useJUnitPlatform()
}

springBoot {
    buildInfo()
}
