// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataFrame.proto

// Protobuf Java Version: 3.25.2
package xyz.chener.napt.common.entity;

public final class DataFrameEntity {
  private DataFrameEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xyz.chener.napt.common.entity.DataFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *  数据
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     * 1TCP  2UDP
     * </pre>
     *
     * <code>int32 requestNtType = 4;</code>
     * @return The requestNtType.
     */
    int getRequestNtType();

    /**
     * <pre>
     *  用于tcp:server portstart 和 remote  映射
     * </pre>
     *
     * <code>string tcpRemoteChannelId = 5;</code>
     * @return The tcpRemoteChannelId.
     */
    java.lang.String getTcpRemoteChannelId();
    /**
     * <pre>
     *  用于tcp:server portstart 和 remote  映射
     * </pre>
     *
     * <code>string tcpRemoteChannelId = 5;</code>
     * @return The bytes for tcpRemoteChannelId.
     */
    com.google.protobuf.ByteString
        getTcpRemoteChannelIdBytes();

    /**
     * <pre>
     * 用于 udp： 服务端接受的地址和远程后端地址做映射
     * </pre>
     *
     * <code>string udpRemoteIp = 6;</code>
     * @return The udpRemoteIp.
     */
    java.lang.String getUdpRemoteIp();
    /**
     * <pre>
     * 用于 udp： 服务端接受的地址和远程后端地址做映射
     * </pre>
     *
     * <code>string udpRemoteIp = 6;</code>
     * @return The bytes for udpRemoteIp.
     */
    com.google.protobuf.ByteString
        getUdpRemoteIpBytes();

    /**
     * <code>int32 udpRemotePort = 7;</code>
     * @return The udpRemotePort.
     */
    int getUdpRemotePort();

    /**
     * <pre>
     * 客户端UID
     * </pre>
     *
     * <code>string clientUid = 8;</code>
     * @return The clientUid.
     */
    java.lang.String getClientUid();
    /**
     * <pre>
     * 客户端UID
     * </pre>
     *
     * <code>string clientUid = 8;</code>
     * @return The bytes for clientUid.
     */
    com.google.protobuf.ByteString
        getClientUidBytes();

    /**
     * <pre>
     * ClientAddress
     * </pre>
     *
     * <code>string clientAddress = 9;</code>
     * @return The clientAddress.
     */
    java.lang.String getClientAddress();
    /**
     * <pre>
     * ClientAddress
     * </pre>
     *
     * <code>string clientAddress = 9;</code>
     * @return The bytes for clientAddress.
     */
    com.google.protobuf.ByteString
        getClientAddressBytes();
  }
  /**
   * Protobuf type {@code xyz.chener.napt.common.entity.DataFrame}
   */
  public static final class DataFrame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xyz.chener.napt.common.entity.DataFrame)
      DataFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataFrame.newBuilder() to construct.
    private DataFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataFrame() {
      message_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      tcpRemoteChannelId_ = "";
      udpRemoteIp_ = "";
      clientUid_ = "";
      clientAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataFrame();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.chener.napt.common.entity.DataFrameEntity.internal_static_xyz_chener_napt_common_entity_DataFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.chener.napt.common.entity.DataFrameEntity.internal_static_xyz_chener_napt_common_entity_DataFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.chener.napt.common.entity.DataFrameEntity.DataFrame.class, xyz.chener.napt.common.entity.DataFrameEntity.DataFrame.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_ = 0;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *  数据
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int REQUESTNTTYPE_FIELD_NUMBER = 4;
    private int requestNtType_ = 0;
    /**
     * <pre>
     * 1TCP  2UDP
     * </pre>
     *
     * <code>int32 requestNtType = 4;</code>
     * @return The requestNtType.
     */
    @java.lang.Override
    public int getRequestNtType() {
      return requestNtType_;
    }

    public static final int TCPREMOTECHANNELID_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tcpRemoteChannelId_ = "";
    /**
     * <pre>
     *  用于tcp:server portstart 和 remote  映射
     * </pre>
     *
     * <code>string tcpRemoteChannelId = 5;</code>
     * @return The tcpRemoteChannelId.
     */
    @java.lang.Override
    public java.lang.String getTcpRemoteChannelId() {
      java.lang.Object ref = tcpRemoteChannelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tcpRemoteChannelId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  用于tcp:server portstart 和 remote  映射
     * </pre>
     *
     * <code>string tcpRemoteChannelId = 5;</code>
     * @return The bytes for tcpRemoteChannelId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTcpRemoteChannelIdBytes() {
      java.lang.Object ref = tcpRemoteChannelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tcpRemoteChannelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UDPREMOTEIP_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object udpRemoteIp_ = "";
    /**
     * <pre>
     * 用于 udp： 服务端接受的地址和远程后端地址做映射
     * </pre>
     *
     * <code>string udpRemoteIp = 6;</code>
     * @return The udpRemoteIp.
     */
    @java.lang.Override
    public java.lang.String getUdpRemoteIp() {
      java.lang.Object ref = udpRemoteIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        udpRemoteIp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用于 udp： 服务端接受的地址和远程后端地址做映射
     * </pre>
     *
     * <code>string udpRemoteIp = 6;</code>
     * @return The bytes for udpRemoteIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUdpRemoteIpBytes() {
      java.lang.Object ref = udpRemoteIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udpRemoteIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UDPREMOTEPORT_FIELD_NUMBER = 7;
    private int udpRemotePort_ = 0;
    /**
     * <code>int32 udpRemotePort = 7;</code>
     * @return The udpRemotePort.
     */
    @java.lang.Override
    public int getUdpRemotePort() {
      return udpRemotePort_;
    }

    public static final int CLIENTUID_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object clientUid_ = "";
    /**
     * <pre>
     * 客户端UID
     * </pre>
     *
     * <code>string clientUid = 8;</code>
     * @return The clientUid.
     */
    @java.lang.Override
    public java.lang.String getClientUid() {
      java.lang.Object ref = clientUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 客户端UID
     * </pre>
     *
     * <code>string clientUid = 8;</code>
     * @return The bytes for clientUid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientUidBytes() {
      java.lang.Object ref = clientUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTADDRESS_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object clientAddress_ = "";
    /**
     * <pre>
     * ClientAddress
     * </pre>
     *
     * <code>string clientAddress = 9;</code>
     * @return The clientAddress.
     */
    @java.lang.Override
    public java.lang.String getClientAddress() {
      java.lang.Object ref = clientAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ClientAddress
     * </pre>
     *
     * <code>string clientAddress = 9;</code>
     * @return The bytes for clientAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientAddressBytes() {
      java.lang.Object ref = clientAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (requestNtType_ != 0) {
        output.writeInt32(4, requestNtType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tcpRemoteChannelId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tcpRemoteChannelId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(udpRemoteIp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, udpRemoteIp_);
      }
      if (udpRemotePort_ != 0) {
        output.writeInt32(7, udpRemotePort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientUid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, clientUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, clientAddress_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (requestNtType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, requestNtType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tcpRemoteChannelId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tcpRemoteChannelId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(udpRemoteIp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, udpRemoteIp_);
      }
      if (udpRemotePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, udpRemotePort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientUid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, clientUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, clientAddress_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xyz.chener.napt.common.entity.DataFrameEntity.DataFrame)) {
        return super.equals(obj);
      }
      xyz.chener.napt.common.entity.DataFrameEntity.DataFrame other = (xyz.chener.napt.common.entity.DataFrameEntity.DataFrame) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getRequestNtType()
          != other.getRequestNtType()) return false;
      if (!getTcpRemoteChannelId()
          .equals(other.getTcpRemoteChannelId())) return false;
      if (!getUdpRemoteIp()
          .equals(other.getUdpRemoteIp())) return false;
      if (getUdpRemotePort()
          != other.getUdpRemotePort()) return false;
      if (!getClientUid()
          .equals(other.getClientUid())) return false;
      if (!getClientAddress()
          .equals(other.getClientAddress())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + REQUESTNTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestNtType();
      hash = (37 * hash) + TCPREMOTECHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getTcpRemoteChannelId().hashCode();
      hash = (37 * hash) + UDPREMOTEIP_FIELD_NUMBER;
      hash = (53 * hash) + getUdpRemoteIp().hashCode();
      hash = (37 * hash) + UDPREMOTEPORT_FIELD_NUMBER;
      hash = (53 * hash) + getUdpRemotePort();
      hash = (37 * hash) + CLIENTUID_FIELD_NUMBER;
      hash = (53 * hash) + getClientUid().hashCode();
      hash = (37 * hash) + CLIENTADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getClientAddress().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xyz.chener.napt.common.entity.DataFrameEntity.DataFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xyz.chener.napt.common.entity.DataFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xyz.chener.napt.common.entity.DataFrame)
        xyz.chener.napt.common.entity.DataFrameEntity.DataFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.chener.napt.common.entity.DataFrameEntity.internal_static_xyz_chener_napt_common_entity_DataFrame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.chener.napt.common.entity.DataFrameEntity.internal_static_xyz_chener_napt_common_entity_DataFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.chener.napt.common.entity.DataFrameEntity.DataFrame.class, xyz.chener.napt.common.entity.DataFrameEntity.DataFrame.Builder.class);
      }

      // Construct using xyz.chener.napt.common.entity.DataFrameEntity.DataFrame.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = 0;
        message_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
        requestNtType_ = 0;
        tcpRemoteChannelId_ = "";
        udpRemoteIp_ = "";
        udpRemotePort_ = 0;
        clientUid_ = "";
        clientAddress_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.chener.napt.common.entity.DataFrameEntity.internal_static_xyz_chener_napt_common_entity_DataFrame_descriptor;
      }

      @java.lang.Override
      public xyz.chener.napt.common.entity.DataFrameEntity.DataFrame getDefaultInstanceForType() {
        return xyz.chener.napt.common.entity.DataFrameEntity.DataFrame.getDefaultInstance();
      }

      @java.lang.Override
      public xyz.chener.napt.common.entity.DataFrameEntity.DataFrame build() {
        xyz.chener.napt.common.entity.DataFrameEntity.DataFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xyz.chener.napt.common.entity.DataFrameEntity.DataFrame buildPartial() {
        xyz.chener.napt.common.entity.DataFrameEntity.DataFrame result = new xyz.chener.napt.common.entity.DataFrameEntity.DataFrame(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(xyz.chener.napt.common.entity.DataFrameEntity.DataFrame result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.requestNtType_ = requestNtType_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.tcpRemoteChannelId_ = tcpRemoteChannelId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.udpRemoteIp_ = udpRemoteIp_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.udpRemotePort_ = udpRemotePort_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.clientUid_ = clientUid_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.clientAddress_ = clientAddress_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.chener.napt.common.entity.DataFrameEntity.DataFrame) {
          return mergeFrom((xyz.chener.napt.common.entity.DataFrameEntity.DataFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.chener.napt.common.entity.DataFrameEntity.DataFrame other) {
        if (other == xyz.chener.napt.common.entity.DataFrameEntity.DataFrame.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getRequestNtType() != 0) {
          setRequestNtType(other.getRequestNtType());
        }
        if (!other.getTcpRemoteChannelId().isEmpty()) {
          tcpRemoteChannelId_ = other.tcpRemoteChannelId_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getUdpRemoteIp().isEmpty()) {
          udpRemoteIp_ = other.udpRemoteIp_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getUdpRemotePort() != 0) {
          setUdpRemotePort(other.getUdpRemotePort());
        }
        if (!other.getClientUid().isEmpty()) {
          clientUid_ = other.clientUid_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getClientAddress().isEmpty()) {
          clientAddress_ = other.clientAddress_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                requestNtType_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                tcpRemoteChannelId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                udpRemoteIp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                udpRemotePort_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                clientUid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                clientAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int requestNtType_ ;
      /**
       * <pre>
       * 1TCP  2UDP
       * </pre>
       *
       * <code>int32 requestNtType = 4;</code>
       * @return The requestNtType.
       */
      @java.lang.Override
      public int getRequestNtType() {
        return requestNtType_;
      }
      /**
       * <pre>
       * 1TCP  2UDP
       * </pre>
       *
       * <code>int32 requestNtType = 4;</code>
       * @param value The requestNtType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestNtType(int value) {

        requestNtType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1TCP  2UDP
       * </pre>
       *
       * <code>int32 requestNtType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestNtType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestNtType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tcpRemoteChannelId_ = "";
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @return The tcpRemoteChannelId.
       */
      public java.lang.String getTcpRemoteChannelId() {
        java.lang.Object ref = tcpRemoteChannelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tcpRemoteChannelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @return The bytes for tcpRemoteChannelId.
       */
      public com.google.protobuf.ByteString
          getTcpRemoteChannelIdBytes() {
        java.lang.Object ref = tcpRemoteChannelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tcpRemoteChannelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @param value The tcpRemoteChannelId to set.
       * @return This builder for chaining.
       */
      public Builder setTcpRemoteChannelId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tcpRemoteChannelId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTcpRemoteChannelId() {
        tcpRemoteChannelId_ = getDefaultInstance().getTcpRemoteChannelId();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @param value The bytes for tcpRemoteChannelId to set.
       * @return This builder for chaining.
       */
      public Builder setTcpRemoteChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tcpRemoteChannelId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object udpRemoteIp_ = "";
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @return The udpRemoteIp.
       */
      public java.lang.String getUdpRemoteIp() {
        java.lang.Object ref = udpRemoteIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          udpRemoteIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @return The bytes for udpRemoteIp.
       */
      public com.google.protobuf.ByteString
          getUdpRemoteIpBytes() {
        java.lang.Object ref = udpRemoteIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          udpRemoteIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @param value The udpRemoteIp to set.
       * @return This builder for chaining.
       */
      public Builder setUdpRemoteIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        udpRemoteIp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUdpRemoteIp() {
        udpRemoteIp_ = getDefaultInstance().getUdpRemoteIp();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @param value The bytes for udpRemoteIp to set.
       * @return This builder for chaining.
       */
      public Builder setUdpRemoteIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        udpRemoteIp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private int udpRemotePort_ ;
      /**
       * <code>int32 udpRemotePort = 7;</code>
       * @return The udpRemotePort.
       */
      @java.lang.Override
      public int getUdpRemotePort() {
        return udpRemotePort_;
      }
      /**
       * <code>int32 udpRemotePort = 7;</code>
       * @param value The udpRemotePort to set.
       * @return This builder for chaining.
       */
      public Builder setUdpRemotePort(int value) {

        udpRemotePort_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 udpRemotePort = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUdpRemotePort() {
        bitField0_ = (bitField0_ & ~0x00000040);
        udpRemotePort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientUid_ = "";
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @return The clientUid.
       */
      public java.lang.String getClientUid() {
        java.lang.Object ref = clientUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @return The bytes for clientUid.
       */
      public com.google.protobuf.ByteString
          getClientUidBytes() {
        java.lang.Object ref = clientUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @param value The clientUid to set.
       * @return This builder for chaining.
       */
      public Builder setClientUid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        clientUid_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientUid() {
        clientUid_ = getDefaultInstance().getClientUid();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @param value The bytes for clientUid to set.
       * @return This builder for chaining.
       */
      public Builder setClientUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        clientUid_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object clientAddress_ = "";
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @return The clientAddress.
       */
      public java.lang.String getClientAddress() {
        java.lang.Object ref = clientAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @return The bytes for clientAddress.
       */
      public com.google.protobuf.ByteString
          getClientAddressBytes() {
        java.lang.Object ref = clientAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @param value The clientAddress to set.
       * @return This builder for chaining.
       */
      public Builder setClientAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        clientAddress_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientAddress() {
        clientAddress_ = getDefaultInstance().getClientAddress();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @param value The bytes for clientAddress to set.
       * @return This builder for chaining.
       */
      public Builder setClientAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        clientAddress_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xyz.chener.napt.common.entity.DataFrame)
    }

    // @@protoc_insertion_point(class_scope:xyz.chener.napt.common.entity.DataFrame)
    private static final xyz.chener.napt.common.entity.DataFrameEntity.DataFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xyz.chener.napt.common.entity.DataFrameEntity.DataFrame();
    }

    public static xyz.chener.napt.common.entity.DataFrameEntity.DataFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataFrame>
        PARSER = new com.google.protobuf.AbstractParser<DataFrame>() {
      @java.lang.Override
      public DataFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataFrame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataFrame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xyz.chener.napt.common.entity.DataFrameEntity.DataFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xyz_chener_napt_common_entity_DataFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xyz_chener_napt_common_entity_DataFrame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017DataFrame.proto\022\035xyz.chener.napt.commo" +
      "n.entity\"\301\001\n\tDataFrame\022\014\n\004code\030\001 \001(\005\022\017\n\007" +
      "message\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\022\025\n\rrequestNt" +
      "Type\030\004 \001(\005\022\032\n\022tcpRemoteChannelId\030\005 \001(\t\022\023" +
      "\n\013udpRemoteIp\030\006 \001(\t\022\025\n\rudpRemotePort\030\007 \001" +
      "(\005\022\021\n\tclientUid\030\010 \001(\t\022\025\n\rclientAddress\030\t" +
      " \001(\tB0\n\035xyz.chener.napt.common.entityB\017D" +
      "ataFrameEntityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xyz_chener_napt_common_entity_DataFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xyz_chener_napt_common_entity_DataFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xyz_chener_napt_common_entity_DataFrame_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", "RequestNtType", "TcpRemoteChannelId", "UdpRemoteIp", "UdpRemotePort", "ClientUid", "ClientAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
