import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.9.25'
    id 'org.jetbrains.kotlin.plugin.spring' version '1.9.25'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.graalvm.buildtools.native' version '0.10.5'
}

group = 'xyz.chener.napt.server'
version = '2.0.0-SNAPSHOT'


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


dependencies {
    implementation project(":common")

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'

    // bugfix:
    // https://github.com/spring-projects/spring-framework/issues/32311
    // 此版本升级到 Hibernate 6.4.4.Final。虽然它包含许多有价值的错误修复，但它在本机映像中无法正常工作。如果您使用的是 GraalVM，则应使用该 hibernate.version 属性暂时将 Hibernate 降级到 6.4.2.Final。
//    implementation 'org.hibernate.orm:hibernate-core:6.4.2.Final'
    implementation 'org.hibernate.orm:hibernate-core:6.6.8.Final'


    implementation 'io.netty:netty-all:4.1.106.Final'
    implementation 'com.google.protobuf:protobuf-java:3.25.2'
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll '-Xjsr305=strict'
    }
}

tasks.named('test') {
    useJUnitPlatform()
}


springBoot {
    buildInfo()
}


// https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#_adding_the_plugin
/*
graalvmNative {
    binaries {
        main{
            imageName = 'napt-server'
        }
    }
}*/
