import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
}

group = 'xyz.chener.napt.common'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '21'
}

dependencies {
    implementation 'com.google.protobuf:protobuf-java:3.25.2'
    implementation 'io.netty:netty-all:4.1.106.Final'
}

tasks.withType(KotlinCompile) {
    kotlinOptions {
        freeCompilerArgs += '-Xjsr305=strict'
        jvmTarget = '21'
    }
}