// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataFrame.proto

package xyz.chener.ext.napt.client.entity;

public final class DataFrameEntity {
  private DataFrameEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xyz.chener.ext.napt.client.entity.DataFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *  数据
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     *  用于server portstart 和 remote  映射
     * </pre>
     *
     * <code>string remoteChannelId = 4;</code>
     * @return The remoteChannelId.
     */
    java.lang.String getRemoteChannelId();
    /**
     * <pre>
     *  用于server portstart 和 remote  映射
     * </pre>
     *
     * <code>string remoteChannelId = 4;</code>
     * @return The bytes for remoteChannelId.
     */
    com.google.protobuf.ByteString
        getRemoteChannelIdBytes();

    /**
     * <pre>
     *  预留字段
     * </pre>
     *
     * <code>string bak1 = 5;</code>
     * @return The bak1.
     */
    java.lang.String getBak1();
    /**
     * <pre>
     *  预留字段
     * </pre>
     *
     * <code>string bak1 = 5;</code>
     * @return The bytes for bak1.
     */
    com.google.protobuf.ByteString
        getBak1Bytes();

    /**
     * <code>string bak2 = 6;</code>
     * @return The bak2.
     */
    java.lang.String getBak2();
    /**
     * <code>string bak2 = 6;</code>
     * @return The bytes for bak2.
     */
    com.google.protobuf.ByteString
        getBak2Bytes();

    /**
     * <code>string bak3 = 7;</code>
     * @return The bak3.
     */
    java.lang.String getBak3();
    /**
     * <code>string bak3 = 7;</code>
     * @return The bytes for bak3.
     */
    com.google.protobuf.ByteString
        getBak3Bytes();

    /**
     * <code>string bak4 = 8;</code>
     * @return The bak4.
     */
    java.lang.String getBak4();
    /**
     * <code>string bak4 = 8;</code>
     * @return The bytes for bak4.
     */
    com.google.protobuf.ByteString
        getBak4Bytes();

    /**
     * <code>string bak5 = 9;</code>
     * @return The bak5.
     */
    java.lang.String getBak5();
    /**
     * <code>string bak5 = 9;</code>
     * @return The bytes for bak5.
     */
    com.google.protobuf.ByteString
        getBak5Bytes();
  }
  /**
   * Protobuf type {@code xyz.chener.ext.napt.client.entity.DataFrame}
   */
  public static final class DataFrame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xyz.chener.ext.napt.client.entity.DataFrame)
      DataFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataFrame.newBuilder() to construct.
    private DataFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataFrame() {
      message_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      remoteChannelId_ = "";
      bak1_ = "";
      bak2_ = "";
      bak3_ = "";
      bak4_ = "";
      bak5_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataFrame();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataFrame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              remoteChannelId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              bak1_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              bak2_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              bak3_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              bak4_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              bak5_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.chener.ext.napt.client.entity.DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.chener.ext.napt.client.entity.DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame.class, xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *  数据
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int REMOTECHANNELID_FIELD_NUMBER = 4;
    private volatile java.lang.Object remoteChannelId_;
    /**
     * <pre>
     *  用于server portstart 和 remote  映射
     * </pre>
     *
     * <code>string remoteChannelId = 4;</code>
     * @return The remoteChannelId.
     */
    @java.lang.Override
    public java.lang.String getRemoteChannelId() {
      java.lang.Object ref = remoteChannelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remoteChannelId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  用于server portstart 和 remote  映射
     * </pre>
     *
     * <code>string remoteChannelId = 4;</code>
     * @return The bytes for remoteChannelId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemoteChannelIdBytes() {
      java.lang.Object ref = remoteChannelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remoteChannelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BAK1_FIELD_NUMBER = 5;
    private volatile java.lang.Object bak1_;
    /**
     * <pre>
     *  预留字段
     * </pre>
     *
     * <code>string bak1 = 5;</code>
     * @return The bak1.
     */
    @java.lang.Override
    public java.lang.String getBak1() {
      java.lang.Object ref = bak1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bak1_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  预留字段
     * </pre>
     *
     * <code>string bak1 = 5;</code>
     * @return The bytes for bak1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBak1Bytes() {
      java.lang.Object ref = bak1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bak1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BAK2_FIELD_NUMBER = 6;
    private volatile java.lang.Object bak2_;
    /**
     * <code>string bak2 = 6;</code>
     * @return The bak2.
     */
    @java.lang.Override
    public java.lang.String getBak2() {
      java.lang.Object ref = bak2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bak2_ = s;
        return s;
      }
    }
    /**
     * <code>string bak2 = 6;</code>
     * @return The bytes for bak2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBak2Bytes() {
      java.lang.Object ref = bak2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bak2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BAK3_FIELD_NUMBER = 7;
    private volatile java.lang.Object bak3_;
    /**
     * <code>string bak3 = 7;</code>
     * @return The bak3.
     */
    @java.lang.Override
    public java.lang.String getBak3() {
      java.lang.Object ref = bak3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bak3_ = s;
        return s;
      }
    }
    /**
     * <code>string bak3 = 7;</code>
     * @return The bytes for bak3.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBak3Bytes() {
      java.lang.Object ref = bak3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bak3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BAK4_FIELD_NUMBER = 8;
    private volatile java.lang.Object bak4_;
    /**
     * <code>string bak4 = 8;</code>
     * @return The bak4.
     */
    @java.lang.Override
    public java.lang.String getBak4() {
      java.lang.Object ref = bak4_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bak4_ = s;
        return s;
      }
    }
    /**
     * <code>string bak4 = 8;</code>
     * @return The bytes for bak4.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBak4Bytes() {
      java.lang.Object ref = bak4_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bak4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BAK5_FIELD_NUMBER = 9;
    private volatile java.lang.Object bak5_;
    /**
     * <code>string bak5 = 9;</code>
     * @return The bak5.
     */
    @java.lang.Override
    public java.lang.String getBak5() {
      java.lang.Object ref = bak5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bak5_ = s;
        return s;
      }
    }
    /**
     * <code>string bak5 = 9;</code>
     * @return The bytes for bak5.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBak5Bytes() {
      java.lang.Object ref = bak5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bak5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (!getRemoteChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, remoteChannelId_);
      }
      if (!getBak1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, bak1_);
      }
      if (!getBak2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, bak2_);
      }
      if (!getBak3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, bak3_);
      }
      if (!getBak4Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, bak4_);
      }
      if (!getBak5Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, bak5_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (!getRemoteChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, remoteChannelId_);
      }
      if (!getBak1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, bak1_);
      }
      if (!getBak2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, bak2_);
      }
      if (!getBak3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, bak3_);
      }
      if (!getBak4Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, bak4_);
      }
      if (!getBak5Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, bak5_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame)) {
        return super.equals(obj);
      }
      xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame other = (xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getRemoteChannelId()
          .equals(other.getRemoteChannelId())) return false;
      if (!getBak1()
          .equals(other.getBak1())) return false;
      if (!getBak2()
          .equals(other.getBak2())) return false;
      if (!getBak3()
          .equals(other.getBak3())) return false;
      if (!getBak4()
          .equals(other.getBak4())) return false;
      if (!getBak5()
          .equals(other.getBak5())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + REMOTECHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getRemoteChannelId().hashCode();
      hash = (37 * hash) + BAK1_FIELD_NUMBER;
      hash = (53 * hash) + getBak1().hashCode();
      hash = (37 * hash) + BAK2_FIELD_NUMBER;
      hash = (53 * hash) + getBak2().hashCode();
      hash = (37 * hash) + BAK3_FIELD_NUMBER;
      hash = (53 * hash) + getBak3().hashCode();
      hash = (37 * hash) + BAK4_FIELD_NUMBER;
      hash = (53 * hash) + getBak4().hashCode();
      hash = (37 * hash) + BAK5_FIELD_NUMBER;
      hash = (53 * hash) + getBak5().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xyz.chener.ext.napt.client.entity.DataFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xyz.chener.ext.napt.client.entity.DataFrame)
        xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.chener.ext.napt.client.entity.DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.chener.ext.napt.client.entity.DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame.class, xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame.Builder.class);
      }

      // Construct using xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        remoteChannelId_ = "";

        bak1_ = "";

        bak2_ = "";

        bak3_ = "";

        bak4_ = "";

        bak5_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.chener.ext.napt.client.entity.DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor;
      }

      @java.lang.Override
      public xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame getDefaultInstanceForType() {
        return xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame.getDefaultInstance();
      }

      @java.lang.Override
      public xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame build() {
        xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame buildPartial() {
        xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame result = new xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame(this);
        result.code_ = code_;
        result.message_ = message_;
        result.data_ = data_;
        result.remoteChannelId_ = remoteChannelId_;
        result.bak1_ = bak1_;
        result.bak2_ = bak2_;
        result.bak3_ = bak3_;
        result.bak4_ = bak4_;
        result.bak5_ = bak5_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame) {
          return mergeFrom((xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame other) {
        if (other == xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getRemoteChannelId().isEmpty()) {
          remoteChannelId_ = other.remoteChannelId_;
          onChanged();
        }
        if (!other.getBak1().isEmpty()) {
          bak1_ = other.bak1_;
          onChanged();
        }
        if (!other.getBak2().isEmpty()) {
          bak2_ = other.bak2_;
          onChanged();
        }
        if (!other.getBak3().isEmpty()) {
          bak3_ = other.bak3_;
          onChanged();
        }
        if (!other.getBak4().isEmpty()) {
          bak4_ = other.bak4_;
          onChanged();
        }
        if (!other.getBak5().isEmpty()) {
          bak5_ = other.bak5_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.lang.Object remoteChannelId_ = "";
      /**
       * <pre>
       *  用于server portstart 和 remote  映射
       * </pre>
       *
       * <code>string remoteChannelId = 4;</code>
       * @return The remoteChannelId.
       */
      public java.lang.String getRemoteChannelId() {
        java.lang.Object ref = remoteChannelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remoteChannelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  用于server portstart 和 remote  映射
       * </pre>
       *
       * <code>string remoteChannelId = 4;</code>
       * @return The bytes for remoteChannelId.
       */
      public com.google.protobuf.ByteString
          getRemoteChannelIdBytes() {
        java.lang.Object ref = remoteChannelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remoteChannelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  用于server portstart 和 remote  映射
       * </pre>
       *
       * <code>string remoteChannelId = 4;</code>
       * @param value The remoteChannelId to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remoteChannelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用于server portstart 和 remote  映射
       * </pre>
       *
       * <code>string remoteChannelId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemoteChannelId() {
        
        remoteChannelId_ = getDefaultInstance().getRemoteChannelId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用于server portstart 和 remote  映射
       * </pre>
       *
       * <code>string remoteChannelId = 4;</code>
       * @param value The bytes for remoteChannelId to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remoteChannelId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bak1_ = "";
      /**
       * <pre>
       *  预留字段
       * </pre>
       *
       * <code>string bak1 = 5;</code>
       * @return The bak1.
       */
      public java.lang.String getBak1() {
        java.lang.Object ref = bak1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bak1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  预留字段
       * </pre>
       *
       * <code>string bak1 = 5;</code>
       * @return The bytes for bak1.
       */
      public com.google.protobuf.ByteString
          getBak1Bytes() {
        java.lang.Object ref = bak1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bak1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  预留字段
       * </pre>
       *
       * <code>string bak1 = 5;</code>
       * @param value The bak1 to set.
       * @return This builder for chaining.
       */
      public Builder setBak1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bak1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  预留字段
       * </pre>
       *
       * <code>string bak1 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBak1() {
        
        bak1_ = getDefaultInstance().getBak1();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  预留字段
       * </pre>
       *
       * <code>string bak1 = 5;</code>
       * @param value The bytes for bak1 to set.
       * @return This builder for chaining.
       */
      public Builder setBak1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bak1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bak2_ = "";
      /**
       * <code>string bak2 = 6;</code>
       * @return The bak2.
       */
      public java.lang.String getBak2() {
        java.lang.Object ref = bak2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bak2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bak2 = 6;</code>
       * @return The bytes for bak2.
       */
      public com.google.protobuf.ByteString
          getBak2Bytes() {
        java.lang.Object ref = bak2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bak2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bak2 = 6;</code>
       * @param value The bak2 to set.
       * @return This builder for chaining.
       */
      public Builder setBak2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bak2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bak2 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBak2() {
        
        bak2_ = getDefaultInstance().getBak2();
        onChanged();
        return this;
      }
      /**
       * <code>string bak2 = 6;</code>
       * @param value The bytes for bak2 to set.
       * @return This builder for chaining.
       */
      public Builder setBak2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bak2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bak3_ = "";
      /**
       * <code>string bak3 = 7;</code>
       * @return The bak3.
       */
      public java.lang.String getBak3() {
        java.lang.Object ref = bak3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bak3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bak3 = 7;</code>
       * @return The bytes for bak3.
       */
      public com.google.protobuf.ByteString
          getBak3Bytes() {
        java.lang.Object ref = bak3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bak3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bak3 = 7;</code>
       * @param value The bak3 to set.
       * @return This builder for chaining.
       */
      public Builder setBak3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bak3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bak3 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBak3() {
        
        bak3_ = getDefaultInstance().getBak3();
        onChanged();
        return this;
      }
      /**
       * <code>string bak3 = 7;</code>
       * @param value The bytes for bak3 to set.
       * @return This builder for chaining.
       */
      public Builder setBak3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bak3_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bak4_ = "";
      /**
       * <code>string bak4 = 8;</code>
       * @return The bak4.
       */
      public java.lang.String getBak4() {
        java.lang.Object ref = bak4_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bak4_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bak4 = 8;</code>
       * @return The bytes for bak4.
       */
      public com.google.protobuf.ByteString
          getBak4Bytes() {
        java.lang.Object ref = bak4_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bak4_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bak4 = 8;</code>
       * @param value The bak4 to set.
       * @return This builder for chaining.
       */
      public Builder setBak4(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bak4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bak4 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBak4() {
        
        bak4_ = getDefaultInstance().getBak4();
        onChanged();
        return this;
      }
      /**
       * <code>string bak4 = 8;</code>
       * @param value The bytes for bak4 to set.
       * @return This builder for chaining.
       */
      public Builder setBak4Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bak4_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bak5_ = "";
      /**
       * <code>string bak5 = 9;</code>
       * @return The bak5.
       */
      public java.lang.String getBak5() {
        java.lang.Object ref = bak5_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bak5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bak5 = 9;</code>
       * @return The bytes for bak5.
       */
      public com.google.protobuf.ByteString
          getBak5Bytes() {
        java.lang.Object ref = bak5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bak5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bak5 = 9;</code>
       * @param value The bak5 to set.
       * @return This builder for chaining.
       */
      public Builder setBak5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bak5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bak5 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearBak5() {
        
        bak5_ = getDefaultInstance().getBak5();
        onChanged();
        return this;
      }
      /**
       * <code>string bak5 = 9;</code>
       * @param value The bytes for bak5 to set.
       * @return This builder for chaining.
       */
      public Builder setBak5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bak5_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xyz.chener.ext.napt.client.entity.DataFrame)
    }

    // @@protoc_insertion_point(class_scope:xyz.chener.ext.napt.client.entity.DataFrame)
    private static final xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame();
    }

    public static xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataFrame>
        PARSER = new com.google.protobuf.AbstractParser<DataFrame>() {
      @java.lang.Override
      public DataFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataFrame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataFrame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataFrame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xyz_chener_ext_napt_client_entity_DataFrame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017DataFrame.proto\022!xyz.chener.ext.napt.c" +
      "lient.entity\"\227\001\n\tDataFrame\022\014\n\004code\030\001 \001(\005" +
      "\022\017\n\007message\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\022\027\n\017remot" +
      "eChannelId\030\004 \001(\t\022\014\n\004bak1\030\005 \001(\t\022\014\n\004bak2\030\006" +
      " \001(\t\022\014\n\004bak3\030\007 \001(\t\022\014\n\004bak4\030\010 \001(\t\022\014\n\004bak5" +
      "\030\t \001(\tB4\n!xyz.chener.ext.napt.client.ent" +
      "ityB\017DataFrameEntityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xyz_chener_ext_napt_client_entity_DataFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", "RemoteChannelId", "Bak1", "Bak2", "Bak3", "Bak4", "Bak5", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
