// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataFrame.proto

package xyz.chener.ext.napt.client.entity;

public final class DataFrameEntity {
  private DataFrameEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xyz.chener.ext.napt.client.entity.DataFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *  数据
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     * 1TCP  2UDP
     * </pre>
     *
     * <code>int32 requestNtType = 4;</code>
     * @return The requestNtType.
     */
    int getRequestNtType();

    /**
     * <pre>
     *  用于tcp:server portstart 和 remote  映射
     * </pre>
     *
     * <code>string tcpRemoteChannelId = 5;</code>
     * @return The tcpRemoteChannelId.
     */
    String getTcpRemoteChannelId();
    /**
     * <pre>
     *  用于tcp:server portstart 和 remote  映射
     * </pre>
     *
     * <code>string tcpRemoteChannelId = 5;</code>
     * @return The bytes for tcpRemoteChannelId.
     */
    com.google.protobuf.ByteString
        getTcpRemoteChannelIdBytes();

    /**
     * <pre>
     * 用于 udp： 服务端接受的地址和远程后端地址做映射
     * </pre>
     *
     * <code>string udpRemoteIp = 6;</code>
     * @return The udpRemoteIp.
     */
    String getUdpRemoteIp();
    /**
     * <pre>
     * 用于 udp： 服务端接受的地址和远程后端地址做映射
     * </pre>
     *
     * <code>string udpRemoteIp = 6;</code>
     * @return The bytes for udpRemoteIp.
     */
    com.google.protobuf.ByteString
        getUdpRemoteIpBytes();

    /**
     * <code>int32 udpRemotePort = 7;</code>
     * @return The udpRemotePort.
     */
    int getUdpRemotePort();

    /**
     * <pre>
     * 客户端UID
     * </pre>
     *
     * <code>string clientUid = 8;</code>
     * @return The clientUid.
     */
    String getClientUid();
    /**
     * <pre>
     * 客户端UID
     * </pre>
     *
     * <code>string clientUid = 8;</code>
     * @return The bytes for clientUid.
     */
    com.google.protobuf.ByteString
        getClientUidBytes();

    /**
     * <pre>
     * ClientAddress
     * </pre>
     *
     * <code>string clientAddress = 9;</code>
     * @return The clientAddress.
     */
    String getClientAddress();
    /**
     * <pre>
     * ClientAddress
     * </pre>
     *
     * <code>string clientAddress = 9;</code>
     * @return The bytes for clientAddress.
     */
    com.google.protobuf.ByteString
        getClientAddressBytes();
  }
  /**
   * Protobuf type {@code xyz.chener.ext.napt.client.entity.DataFrame}
   */
  public static final class DataFrame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xyz.chener.ext.napt.client.entity.DataFrame)
      DataFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataFrame.newBuilder() to construct.
    private DataFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataFrame() {
      message_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      tcpRemoteChannelId_ = "";
      udpRemoteIp_ = "";
      clientUid_ = "";
      clientAddress_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataFrame();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataFrame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            case 32: {

              requestNtType_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              tcpRemoteChannelId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              udpRemoteIp_ = s;
              break;
            }
            case 56: {

              udpRemotePort_ = input.readInt32();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              clientUid_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              clientAddress_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataFrame.class, Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *  数据
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int REQUESTNTTYPE_FIELD_NUMBER = 4;
    private int requestNtType_;
    /**
     * <pre>
     * 1TCP  2UDP
     * </pre>
     *
     * <code>int32 requestNtType = 4;</code>
     * @return The requestNtType.
     */
    @Override
    public int getRequestNtType() {
      return requestNtType_;
    }

    public static final int TCPREMOTECHANNELID_FIELD_NUMBER = 5;
    private volatile Object tcpRemoteChannelId_;
    /**
     * <pre>
     *  用于tcp:server portstart 和 remote  映射
     * </pre>
     *
     * <code>string tcpRemoteChannelId = 5;</code>
     * @return The tcpRemoteChannelId.
     */
    @Override
    public String getTcpRemoteChannelId() {
      Object ref = tcpRemoteChannelId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tcpRemoteChannelId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  用于tcp:server portstart 和 remote  映射
     * </pre>
     *
     * <code>string tcpRemoteChannelId = 5;</code>
     * @return The bytes for tcpRemoteChannelId.
     */
    @Override
    public com.google.protobuf.ByteString
        getTcpRemoteChannelIdBytes() {
      Object ref = tcpRemoteChannelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tcpRemoteChannelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UDPREMOTEIP_FIELD_NUMBER = 6;
    private volatile Object udpRemoteIp_;
    /**
     * <pre>
     * 用于 udp： 服务端接受的地址和远程后端地址做映射
     * </pre>
     *
     * <code>string udpRemoteIp = 6;</code>
     * @return The udpRemoteIp.
     */
    @Override
    public String getUdpRemoteIp() {
      Object ref = udpRemoteIp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        udpRemoteIp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用于 udp： 服务端接受的地址和远程后端地址做映射
     * </pre>
     *
     * <code>string udpRemoteIp = 6;</code>
     * @return The bytes for udpRemoteIp.
     */
    @Override
    public com.google.protobuf.ByteString
        getUdpRemoteIpBytes() {
      Object ref = udpRemoteIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        udpRemoteIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UDPREMOTEPORT_FIELD_NUMBER = 7;
    private int udpRemotePort_;
    /**
     * <code>int32 udpRemotePort = 7;</code>
     * @return The udpRemotePort.
     */
    @Override
    public int getUdpRemotePort() {
      return udpRemotePort_;
    }

    public static final int CLIENTUID_FIELD_NUMBER = 8;
    private volatile Object clientUid_;
    /**
     * <pre>
     * 客户端UID
     * </pre>
     *
     * <code>string clientUid = 8;</code>
     * @return The clientUid.
     */
    @Override
    public String getClientUid() {
      Object ref = clientUid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 客户端UID
     * </pre>
     *
     * <code>string clientUid = 8;</code>
     * @return The bytes for clientUid.
     */
    @Override
    public com.google.protobuf.ByteString
        getClientUidBytes() {
      Object ref = clientUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTADDRESS_FIELD_NUMBER = 9;
    private volatile Object clientAddress_;
    /**
     * <pre>
     * ClientAddress
     * </pre>
     *
     * <code>string clientAddress = 9;</code>
     * @return The clientAddress.
     */
    @Override
    public String getClientAddress() {
      Object ref = clientAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ClientAddress
     * </pre>
     *
     * <code>string clientAddress = 9;</code>
     * @return The bytes for clientAddress.
     */
    @Override
    public com.google.protobuf.ByteString
        getClientAddressBytes() {
      Object ref = clientAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (requestNtType_ != 0) {
        output.writeInt32(4, requestNtType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tcpRemoteChannelId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tcpRemoteChannelId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(udpRemoteIp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, udpRemoteIp_);
      }
      if (udpRemotePort_ != 0) {
        output.writeInt32(7, udpRemotePort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientUid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, clientUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, clientAddress_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (requestNtType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, requestNtType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tcpRemoteChannelId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tcpRemoteChannelId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(udpRemoteIp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, udpRemoteIp_);
      }
      if (udpRemotePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, udpRemotePort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientUid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, clientUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, clientAddress_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataFrame)) {
        return super.equals(obj);
      }
      DataFrame other = (DataFrame) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getRequestNtType()
          != other.getRequestNtType()) return false;
      if (!getTcpRemoteChannelId()
          .equals(other.getTcpRemoteChannelId())) return false;
      if (!getUdpRemoteIp()
          .equals(other.getUdpRemoteIp())) return false;
      if (getUdpRemotePort()
          != other.getUdpRemotePort()) return false;
      if (!getClientUid()
          .equals(other.getClientUid())) return false;
      if (!getClientAddress()
          .equals(other.getClientAddress())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + REQUESTNTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestNtType();
      hash = (37 * hash) + TCPREMOTECHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getTcpRemoteChannelId().hashCode();
      hash = (37 * hash) + UDPREMOTEIP_FIELD_NUMBER;
      hash = (53 * hash) + getUdpRemoteIp().hashCode();
      hash = (37 * hash) + UDPREMOTEPORT_FIELD_NUMBER;
      hash = (53 * hash) + getUdpRemotePort();
      hash = (37 * hash) + CLIENTUID_FIELD_NUMBER;
      hash = (53 * hash) + getClientUid().hashCode();
      hash = (37 * hash) + CLIENTADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getClientAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xyz.chener.ext.napt.client.entity.DataFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xyz.chener.ext.napt.client.entity.DataFrame)
        DataFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataFrame.class, Builder.class);
      }

      // Construct using xyz.chener.ext.napt.client.entity.DataFrameEntity.DataFrame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        requestNtType_ = 0;

        tcpRemoteChannelId_ = "";

        udpRemoteIp_ = "";

        udpRemotePort_ = 0;

        clientUid_ = "";

        clientAddress_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataFrameEntity.internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor;
      }

      @Override
      public DataFrame getDefaultInstanceForType() {
        return DataFrame.getDefaultInstance();
      }

      @Override
      public DataFrame build() {
        DataFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DataFrame buildPartial() {
        DataFrame result = new DataFrame(this);
        result.code_ = code_;
        result.message_ = message_;
        result.data_ = data_;
        result.requestNtType_ = requestNtType_;
        result.tcpRemoteChannelId_ = tcpRemoteChannelId_;
        result.udpRemoteIp_ = udpRemoteIp_;
        result.udpRemotePort_ = udpRemotePort_;
        result.clientUid_ = clientUid_;
        result.clientAddress_ = clientAddress_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataFrame) {
          return mergeFrom((DataFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataFrame other) {
        if (other == DataFrame.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getRequestNtType() != 0) {
          setRequestNtType(other.getRequestNtType());
        }
        if (!other.getTcpRemoteChannelId().isEmpty()) {
          tcpRemoteChannelId_ = other.tcpRemoteChannelId_;
          onChanged();
        }
        if (!other.getUdpRemoteIp().isEmpty()) {
          udpRemoteIp_ = other.udpRemoteIp_;
          onChanged();
        }
        if (other.getUdpRemotePort() != 0) {
          setUdpRemotePort(other.getUdpRemotePort());
        }
        if (!other.getClientUid().isEmpty()) {
          clientUid_ = other.clientUid_;
          onChanged();
        }
        if (!other.getClientAddress().isEmpty()) {
          clientAddress_ = other.clientAddress_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataFrame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataFrame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int requestNtType_ ;
      /**
       * <pre>
       * 1TCP  2UDP
       * </pre>
       *
       * <code>int32 requestNtType = 4;</code>
       * @return The requestNtType.
       */
      @Override
      public int getRequestNtType() {
        return requestNtType_;
      }
      /**
       * <pre>
       * 1TCP  2UDP
       * </pre>
       *
       * <code>int32 requestNtType = 4;</code>
       * @param value The requestNtType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestNtType(int value) {
        
        requestNtType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1TCP  2UDP
       * </pre>
       *
       * <code>int32 requestNtType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestNtType() {
        
        requestNtType_ = 0;
        onChanged();
        return this;
      }

      private Object tcpRemoteChannelId_ = "";
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @return The tcpRemoteChannelId.
       */
      public String getTcpRemoteChannelId() {
        Object ref = tcpRemoteChannelId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tcpRemoteChannelId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @return The bytes for tcpRemoteChannelId.
       */
      public com.google.protobuf.ByteString
          getTcpRemoteChannelIdBytes() {
        Object ref = tcpRemoteChannelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tcpRemoteChannelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @param value The tcpRemoteChannelId to set.
       * @return This builder for chaining.
       */
      public Builder setTcpRemoteChannelId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tcpRemoteChannelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTcpRemoteChannelId() {
        
        tcpRemoteChannelId_ = getDefaultInstance().getTcpRemoteChannelId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用于tcp:server portstart 和 remote  映射
       * </pre>
       *
       * <code>string tcpRemoteChannelId = 5;</code>
       * @param value The bytes for tcpRemoteChannelId to set.
       * @return This builder for chaining.
       */
      public Builder setTcpRemoteChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tcpRemoteChannelId_ = value;
        onChanged();
        return this;
      }

      private Object udpRemoteIp_ = "";
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @return The udpRemoteIp.
       */
      public String getUdpRemoteIp() {
        Object ref = udpRemoteIp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          udpRemoteIp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @return The bytes for udpRemoteIp.
       */
      public com.google.protobuf.ByteString
          getUdpRemoteIpBytes() {
        Object ref = udpRemoteIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          udpRemoteIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @param value The udpRemoteIp to set.
       * @return This builder for chaining.
       */
      public Builder setUdpRemoteIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        udpRemoteIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUdpRemoteIp() {
        
        udpRemoteIp_ = getDefaultInstance().getUdpRemoteIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于 udp： 服务端接受的地址和远程后端地址做映射
       * </pre>
       *
       * <code>string udpRemoteIp = 6;</code>
       * @param value The bytes for udpRemoteIp to set.
       * @return This builder for chaining.
       */
      public Builder setUdpRemoteIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        udpRemoteIp_ = value;
        onChanged();
        return this;
      }

      private int udpRemotePort_ ;
      /**
       * <code>int32 udpRemotePort = 7;</code>
       * @return The udpRemotePort.
       */
      @Override
      public int getUdpRemotePort() {
        return udpRemotePort_;
      }
      /**
       * <code>int32 udpRemotePort = 7;</code>
       * @param value The udpRemotePort to set.
       * @return This builder for chaining.
       */
      public Builder setUdpRemotePort(int value) {
        
        udpRemotePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 udpRemotePort = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUdpRemotePort() {
        
        udpRemotePort_ = 0;
        onChanged();
        return this;
      }

      private Object clientUid_ = "";
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @return The clientUid.
       */
      public String getClientUid() {
        Object ref = clientUid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientUid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @return The bytes for clientUid.
       */
      public com.google.protobuf.ByteString
          getClientUidBytes() {
        Object ref = clientUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @param value The clientUid to set.
       * @return This builder for chaining.
       */
      public Builder setClientUid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientUid() {
        
        clientUid_ = getDefaultInstance().getClientUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端UID
       * </pre>
       *
       * <code>string clientUid = 8;</code>
       * @param value The bytes for clientUid to set.
       * @return This builder for chaining.
       */
      public Builder setClientUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientUid_ = value;
        onChanged();
        return this;
      }

      private Object clientAddress_ = "";
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @return The clientAddress.
       */
      public String getClientAddress() {
        Object ref = clientAddress_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @return The bytes for clientAddress.
       */
      public com.google.protobuf.ByteString
          getClientAddressBytes() {
        Object ref = clientAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @param value The clientAddress to set.
       * @return This builder for chaining.
       */
      public Builder setClientAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientAddress() {
        
        clientAddress_ = getDefaultInstance().getClientAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ClientAddress
       * </pre>
       *
       * <code>string clientAddress = 9;</code>
       * @param value The bytes for clientAddress to set.
       * @return This builder for chaining.
       */
      public Builder setClientAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientAddress_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xyz.chener.ext.napt.client.entity.DataFrame)
    }

    // @@protoc_insertion_point(class_scope:xyz.chener.ext.napt.client.entity.DataFrame)
    private static final DataFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataFrame();
    }

    public static DataFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataFrame>
        PARSER = new com.google.protobuf.AbstractParser<DataFrame>() {
      @Override
      public DataFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataFrame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataFrame> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DataFrame> getParserForType() {
      return PARSER;
    }

    @Override
    public DataFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xyz_chener_ext_napt_client_entity_DataFrame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017DataFrame.proto\022!xyz.chener.ext.napt.c" +
      "lient.entity\"\301\001\n\tDataFrame\022\014\n\004code\030\001 \001(\005" +
      "\022\017\n\007message\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\022\025\n\rreque" +
      "stNtType\030\004 \001(\005\022\032\n\022tcpRemoteChannelId\030\005 \001" +
      "(\t\022\023\n\013udpRemoteIp\030\006 \001(\t\022\025\n\rudpRemotePort" +
      "\030\007 \001(\005\022\021\n\tclientUid\030\010 \001(\t\022\025\n\rclientAddre" +
      "ss\030\t \001(\tB4\n!xyz.chener.ext.napt.client.e" +
      "ntityB\017DataFrameEntityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xyz_chener_ext_napt_client_entity_DataFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xyz_chener_ext_napt_client_entity_DataFrame_descriptor,
        new String[] { "Code", "Message", "Data", "RequestNtType", "TcpRemoteChannelId", "UdpRemoteIp", "UdpRemotePort", "ClientUid", "ClientAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
